---
name: Lint Code Base

on:
  push:
    branches-ignore: main
  pull_request:
    branches: main

jobs:
  lint:
    uses: ./.github/workflows/reusable-superlinter.yml
    with:
      validate_all_codebase: true
