---
name: Deploy
on:
  workflow_call:
    inputs:
      name:
        default: ${{ github.repository }}
        type: string
        description: Name of image to build ( ie. ghcr.io/{{ name }}:tag )
      image_name:
        type: string
        description: Optional suffix for name ( ie. ghcr.io/{{name}}/{{image_name}}:tag )
      dockerfile:
        default: "./Dockerfile"
        type: string
        description: Path to the Dockerfile to build.
      platforms:
        default: "linux/amd64"
        type: string
        description: Platforms to build image for
      build_context:
        default: "."
        type: string
        description: Directory to set as the docker build context.
      tag_suffix:
        type: string
        description: Suffix to add to all tags
      push:
        default: true
        type: boolean
        description: Enable pushing to registry

jobs:
  build_image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Log in to the Container registry
        uses: docker/login-action@49ed152c8eca782a232dede0303416e8f356c37b
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/${{ inputs.name }}${{ inputs.image_name && '/'}}${{ inputs.image_name }}
          tags: |
            type=sha,prefix=,suffix=${{ inputs.tag_suffix && format('-{0}', inputs.tag_suffix) }}
            type=ref,event=branch,suffix=${{ inputs.tag_suffix && format('-{0}', inputs.tag_suffix) }}
            type=ref,event=pr,suffix=${{ inputs.tag_suffix && format('-{0}', inputs.tag_suffix) }}
            type=raw,value=latest,enable=${{ endsWith(github.ref, github.event.repository.default_branch) }},suffix=${{ inputs.tag_suffix && format('-{0}', inputs.tag_suffix) }}
          labels: |
            org.opencontainers.image.url=https://github.com/${{ github.repository }}/tree/${{ github.sha }}
            org.opencontainers.image.source=https://github.com/${{ github.repository }}/tree/${{ github.sha }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: ${{ inputs.platforms }}
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v3
        with:
          file: ${{ inputs.dockerfile }}
          context: ${{ inputs.build_context }}
          platforms: ${{ inputs.platforms }}
          push: ${{ inputs.push }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
